# Generated by Django 2.2 on 2020-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='catagory_name',
        ),
    ]
