# Generated by Django 2.2 on 2020-05-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20200501_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
