# Generated by Django 3.0.5 on 2020-07-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_auto_20200712_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(default='Image-Coming-Soon.jpg', upload_to='item_images'),
        ),
    ]
