# Generated by Django 3.0.5 on 2020-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0006_auto_20200713_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.CharField(default='https://i1.wp.com/gchs.org/wp-content/uploads/Image-Coming-Soon-Placeholder.png?fit=350%2C350&ssl=1', max_length=200),
        ),
    ]
