# Generated by Django 3.0.5 on 2020-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0007_auto_20200715_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
